### ISSUE TITLE
[Docs] what is the motivation for this library?

### ISSUE THREAD

**Issue by chipweinberger** [ivoleitao/shadertoy#10]
Shaders have been added to flutter, yes. But they cannot be compiled at runtime. 

see: https://github.com/flutter/flutter/issues/135340#issuecomment-1751513427

**Without being able to actually *run* the shaders in Flutter, what is the motivation for this app?**

I suppose you could still run them in a web platform view? For example, with: https://github.com/chipweinberger/ShaderToyLite.js

**Comment by ivoleitao** [comment]
Hi, this library does a bit more than what I communicate on the docs, but I dont advertise it on purpose. It's able to scrape the complete shadertoy website and store all the shaders in a sqlite database. 

I don't want to advertise that to avoid creating problems to the shadertoy site as it creates a lot of traffic. As a final goal my I idea is to mix this library with a rust wgpu / naga backend and specific platform views as Im aware like you mentioned that I cant do runtime compilation.

This is mostly a hobby so that other part is just something that I want to do not necessarily something that Ive started working on
